### ==========================================
### 1. Отримання JWT токенів
### ==========================================

### Отримати токен для Адміністратора (admin)
# @name loginAdmin
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

### Отримати токен для звичайного користувача (skhmelyuk)
# @name loginUser
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "skhmelyuk",
    "password": "qwerty_1985"
}

### Оновлення access токена через refresh
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "{{loginAdmin.response.body.refresh}}"
}



### ==========================================
### 2. Публічні запити (Товари - Доступно всім)
### ==========================================

### Перегляд списку товарів (без авторизації) -> 200 OK
GET http://127.0.0.1:8000/api/products/
Content-Type: application/json

###

### Перегляд одного товару (без авторизації) -> 200 OK
GET http://127.0.0.1:8000/api/products/1/
Content-Type: application/json


### ==========================================
### 3. Зміна товарів (Тільки для Адміністратора)
### ==========================================

### Спроба створити товар без токена -> 401 Unauthorized
POST http://127.0.0.1:8000/api/products/
Content-Type: application/json

{
    "name": "Анонімний товар",
    "description": "Тест",
    "price": "100.00",
    "stock": 10
}

###

### Спроба створити товар звичайним користувачем -> 403 Forbidden
POST http://127.0.0.1:8000/api/products/
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.access}}

{
    "name": "Товар від клієнта",
    "description": "Спроба створення без прав адміністратора",
    "price": "250.00",
    "stock": 5
}

###

### Створення товару Адміністратором -> 201 Created
POST http://127.0.0.1:8000/api/products/
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.access}}

{
    "name": "Чай",
    "description": "Високогірний органічний зелений чай",
    "price": "120.00",
    "stock": 50
}

###

### Оновлення товару Адміністратором -> 200 OK
PATCH http://127.0.0.1:8000/api/products/19/
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.access}}

{
    "stock": 25,
    "price": "46000.00"
}

###

### Видалення товару Адміністратором -> 204 No Content
DELETE http://127.0.0.1:8000/api/products/19/
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.access}}


### ==========================================
### 4. Замовлення (Тільки для авторизованих)
### ==========================================

### Спроба переглянути замовлення без токена -> 401 Unauthorized
GET http://127.0.0.1:8000/api/orders/
Content-Type: application/json

###

### Перегляд замовлень звичайним користувачем (бачить лише власні) -> 200 OK
GET http://127.0.0.1:8000/api/orders/
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.access}}

###

### Перегляд замовлень Адміністратором (бачить усі замовлення магазину) -> 200 OK
GET http://127.0.0.1:8000/api/orders/
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.access}}


### Перегляд замовлень звичайним користувачем (бачить лише власні) -> 200 OK
GET http://127.0.0.1:8000/api/user-orders/
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.access}}

###

GET http://127.0.0.1:8000/
Content-Type: application/json
