[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
markers =
    django_db: тест вимагає доступу до бази даних
    auth: тести автентифікації
    products: тести товарів
    orders: тести замовлень